[package]
name = "nats-source"
group = "infinyon"
version = "0.1.5"
apiVersion = "0.1.0"
fluvio = "0.10.14"
description = "Nats source connector"
license = "MIT OR Apache-2.0"
visibility = "public"

[direction]
source = true

[deployment]
binary = "nats-source"

[custom]
name = "nats"
required = ["url", "subject"]

[custom.properties.url]
title = "Host"
description = "Nats host"
type = "string"

[custom.properties.subject]
title = "Subject"
description = "Nats Subject"
type = "string"
