[package]
name = "nats-fluvio-integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.24.1"
tokio = { version = "1.34.0", features = ["full"] }
